# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RandomUserGenerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RandomUserGenerator
  pod 'RandomUserSwift', '~> 0.02' 
end
